import { MESSAGE, LOTTO_NUMBER_SEPARATOR } from './display';
import {
  LOTTO_UNIT_PRICE,
  MIN_MONETARY_UNIT,
  LOTTO_MIN_NUMBER,
  LOTTO_MAX_NUMBER,
  LOTTO_NUMBERS_LENGTH,
  BONUS_NUMBER_LENGTH,
  BONUS_CHECK_REQUIRED_COUNT,
  BONUS_COUNT,
  RESULT_TABLE_DATA,
} from './lottoRules';
import dummyDrawNumber from './dummyData.json';

export {
  MESSAGE,
  LOTTO_NUMBER_SEPARATOR,
  LOTTO_UNIT_PRICE,
  MIN_MONETARY_UNIT,
  LOTTO_MIN_NUMBER,
  LOTTO_MAX_NUMBER,
  LOTTO_NUMBERS_LENGTH,
  BONUS_NUMBER_LENGTH,
  BONUS_CHECK_REQUIRED_COUNT,
  BONUS_COUNT,
  RESULT_TABLE_DATA,
  dummyDrawNumber,
};
