const LOTTERY_BALL_LENGTH = 6;
const BONUS_BALL_LENGTH = 1;
const MIN_LOTTO_NUMBER = 1;
const MAX_LOTTO_NUMBER = 45;
const LOTTERY_PRICE = 1000;

export {
  LOTTERY_BALL_LENGTH,
  BONUS_BALL_LENGTH,
  MIN_LOTTO_NUMBER,
  MAX_LOTTO_NUMBER,
  LOTTERY_PRICE,
};
