export const UNIT_AMOUNT = 1000;
export const MIN_LOTTO_NUMBER = 1;
export const MAX_LOTTO_NUMBER = 45;
export const LOTTO_NUMBER_COUNT = 6;
export const BONUS_NUMBER_COUNT = 1;
export const WINNING_NUMBER_COUNT = LOTTO_NUMBER_COUNT + BONUS_NUMBER_COUNT;

export const HIT_COUNT = {
  NONE: 0,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
};

export const WINNING_RANK = {
  NONE: 0,
  FIRST: 1,
  SECOND: 2,
  THIRD: 3,
  FOURTH: 4,
  FIFTH: 5,
};

export const WINNING_PRICE = {
  FIRST: 2e9,
  SECOND: 3e7,
  THIRD: 15e5,
  FOURTH: 5e4,
  FIFTH: 5e3,
  NONE: 0,
};

export const PROFITS = {
  [WINNING_RANK.FIRST]: WINNING_PRICE.FIRST,
  [WINNING_RANK.SECOND]: WINNING_PRICE.SECOND,
  [WINNING_RANK.THIRD]: WINNING_PRICE.THIRD,
  [WINNING_RANK.FOURTH]: WINNING_PRICE.FOURTH,
  [WINNING_RANK.FIFTH]: WINNING_PRICE.FIFTH,
  [WINNING_RANK.NONE]: WINNING_PRICE.NONE,
};

export const RANK = {
  [HIT_COUNT.SIX]: WINNING_RANK.FIRST,
  [HIT_COUNT.FIVE]: WINNING_RANK.THIRD,
  [HIT_COUNT.FOUR]: WINNING_RANK.FOURTH,
  [HIT_COUNT.THREE]: WINNING_RANK.FIFTH,
  [HIT_COUNT.TWO]: WINNING_RANK.NONE,
  [HIT_COUNT.ONE]: WINNING_RANK.NONE,
  [HIT_COUNT.NONE]: WINNING_RANK.NONE,
};
